name: Test CI

on:
  push:
    branches:
      - 'main'
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose build
        id: docker-build
        run: docker-compose build
      - name: Docker compose run
        id: docker-run
        run: docker-compose run --rm hello
